# https://www.appveyor.com/docs/appveyor-yml/
# https://ci.appveyor.com/tools/validate-yaml/
# https://www.appveyor.com/docs/environment-variables/

# Without this, the following error shows up:
# "Specify a project or solution file. The directory does not contain a project or solution file."
build: off

branches:
  only:
    - master
    - appveyor

test_script:
- ps: |
    @{
	  APPVEYOR = $env:APPVEYOR
	  APPVEYOR_BUILD_ID = $env:APPVEYOR_BUILD_ID
	  APPVEYOR_BUILD_NUMBER = $env:APPVEYOR_BUILD_NUMBER
	  APPVEYOR_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION
	  APPVEYOR_PULL_REQUEST_NUMBER = $env:APPVEYOR_PULL_REQUEST_NUMBER
	  APPVEYOR_REPO_BRANCH = $env:APPVEYOR_REPO_BRANCH
	  APPVEYOR_REPO_COMMIT_AUTHOR = $env:APPVEYOR_REPO_COMMIT_AUTHOR
    }
